logging:
  level:
    org.springframework: INFO
    com.xieziming: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://blog.xieziming/xieziming?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: xieziming
    password: xieziming
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-active: 4
      test-on-borrow: true
      initial-size: 2
      test-while-idle: true